"""Toggle-able atmospheric disturbance model: constant wind + Dryden gusts.

Disabled by default — SimConfig.wind = None produces bit-identical runs to a
build without this module. Enable via config:

    wind = {
        'constant_ned': [wn, we, wd],      # steady wind, NED [m/s]
        'dryden': {                        # optional stochastic gusts
            'V':     20.0,                 # reference airspeed [m/s]
            'sigma': [1.06, 1.06, 0.7],    # gust intensities  [m/s]
            'L':     [200.0, 200.0, 50.0], # turbulence scale lengths [m]
        },
        'seed': 42,                        # REQUIRED with dryden — reproducible
    }

Dryden implementation notes
---------------------------
Each axis is generated by the first-order Gauss–Markov approximation of the
Dryden spectra (MIL-F-8785C), discretised exactly:

    w[k+1] = phi * w[k] + sigma * sqrt(1 - phi^2) * eta[k],
    phi    = exp(-V * dt / L)

This is the standard first-order surrogate for the u-channel filter applied
per-axis (the full spec uses second-order forms for v/w). Gusts are expressed
in NED axes and held constant across the four RK4 substeps of each
integration step (zero-order hold).

The random stream is an isolated np.random.default_rng(seed): the same seed
always reproduces the same gust history for a given (dt, parameters).
"""
import numpy as np


class WindModel:
    """Per-run wind provider. Construct from SimConfig.wind dict + dt."""

    def __init__(self, spec, dt):
        if not isinstance(spec, dict):
            raise TypeError('wind spec must be a dict (or None to disable)')
        self.constant = np.asarray(spec.get('constant_ned', [0.0, 0.0, 0.0]),
                                   dtype=float)
        if self.constant.shape != (3,):
            raise ValueError('constant_ned must be a 3-vector (NED, m/s)')

        self._dryden = None
        dry = spec.get('dryden')
        if dry:
            if 'seed' not in spec:
                raise ValueError('wind.seed is required when dryden gusts are '
                                 'enabled — unseeded runs are unreproducible')
            V     = float(dry.get('V', 20.0))
            sigma = np.asarray(dry.get('sigma', [1.06, 1.06, 0.7]), dtype=float)
            L     = np.asarray(dry.get('L', [200.0, 200.0, 50.0]), dtype=float)
            if V <= 0 or np.any(L <= 0) or np.any(sigma < 0):
                raise ValueError('dryden requires V > 0, L > 0, sigma >= 0')
            phi = np.exp(-V * dt / L)
            self._dryden = {
                'phi':   phi,
                'scale': sigma * np.sqrt(1.0 - phi**2),
                'state': np.zeros(3),
                'rng':   np.random.default_rng(spec['seed']),
            }

        self._current = self.constant.copy()

    def step(self):
        """Advance one integration step; returns wind NED (3,) [m/s]."""
        if self._dryden is not None:
            d = self._dryden
            d['state'] = (d['phi'] * d['state']
                          + d['scale'] * d['rng'].standard_normal(3))
            self._current = self.constant + d['state']
        return self._current

    def describe(self):
        out = {'constant_ned_ms': self.constant.tolist()}
        if self._dryden is not None:
            out['dryden'] = 'first-order Gauss-Markov (seeded)'
        return out
